### ISSUE TITLE
Phil Washington has incorrect membership end_date

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#318]
Phil Washington has an incorrect membership end_date ("2020-06-30") for the Ad Hoc Sustainability Committee in the OCD API: 
https://ocd.datamade.us/ocd-organization/f40445d3-7036-49df-992c-4ba218b8d6b4/

The Legistar API shows the correct end_date ("2018-06-30"): http://webapi.legistar.com/v1/metro/bodies/176/officerecords

Determine why the scraper does not know about the new membership end_date.

**Comment by reginafcompton** [comment]
The scraper seems to behave as expected. A brief summary of the code:

(1) Iterate over all [“bodies”](http://webapi.legistar.com/v1/metro/bodies):
https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/people.py#L95
https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/people.py#L60

(2) For each body iterate over all [“Offices”](http://webapi.legistar.com/v1/metro/bodies/176/officerecords):
https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/people.py#L108
https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/people.py#L66

**Comment by reginafcompton** [comment]
_Server logs_

The server logs (i.e., `tmp/lametro.log`, etc.) contain recently successful runs of the people scraper, for instance, from `tmp/lametro.log.1`:
```
people scrape:
  duration:  0:01:03.673932
  objects:
    membership: 381
    organization: 12
    person: 33
import:
  bill: 0 new 0 updated 107 noop
  event: 0 new 10 updated 272 noop
  jurisdiction: 0 new 0 updated 1 noop
  membership: 26 new 0 updated 355 noop
  organization: 1 new 0 updated 14 noop
  person: 0 new 0 updated 33 noop
  post: 0 new 0 updated 16 noop
  vote_event: 0 new 0 updated 30 noop
```

And I do not see errors surrounding the scrape of the committee and memberships:
```
19:18:47 INFO pupa: save organization Ad Hoc Congestion Reduction Committee as organization_a512da34-830d-11e8-87fb-122a3d729da3.json
19:18:47 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/bodies/176/OfficeRecords
19:18:48 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/persons/289
19:18:49 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/persons/881
19:18:50 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/persons/1044
19:18:51 INFO scrapelib: GET - http://webapi.legistar.com/v1/metro/persons/1983
19:18:52 INFO pupa: save organization Ad Hoc Sustainability Committee as organization_a5a0cdb2-830d-11e8-87fb-122a3d729da3.json
```
However, the logs only contain a timestamp _without_ a date. So, it's fairly difficult to determine  if the scraper erred on 7/3/18, when Metro made the change to Phil Washington's membership. (Let's open an issue to include this in the pupa update: https://github.com/opencivicdata/pupa/blob/master/pupa/cli/commands/update.py)
